name: CI

on: [push]

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            sudo git config --global --add safe.directory ${{ secrets.PROJECT_PATH }}
            cd ${{ secrets.PROJECT_PATH }}
            sudo git pull origin main
            composer upgrade
            php artisan migrate


            # Correction des permissions Laravel
            sudo chown -R www-data:www-data ${{ secrets.PROJECT_PATH }}/storage
            sudo chmod -R 775 ${{ secrets.PROJECT_PATH }}/storage
            sudo chown -R www-data:www-data ${{ secrets.PROJECT_PATH }}/bootstrap/cache
            sudo chmod -R 775 ${{ secrets.PROJECT_PATH }}/bootstrap/cache

            sudo systemctl restart php8.2-fpm
            sudo systemctl restart nginx
