name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add VPS key to known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "51.89.150.209 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB3/PBT3J1PK9ENnPzpDiBveROwoD1i/9zkMU3rYb3NBh4rEyq" >> ~/.ssh/known_hosts

      - name: Test SSH manually
        run: |
          echo "$PRIVATE_KEY" > id_test_key
          chmod 600 id_test_key
          ssh -i id_test_key -p 6666 -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} "echo ✅ Connexion SSH réussie !"
        env:
          PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}

      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 6666
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git pull origin main
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            sudo systemctl restart php8.2-fpm
            sudo systemctl restart nginx
